### ISSUE TITLE
namespace shading

### ISSUE THREAD

**Issue by geoHeil** [jiayuasu/JTSplus#8]
How can I include this library (via geospark) in a java project which is using geotools library as well? Both geospark and geotools require JTS in one version or the other. However, JTSplus is sort of interfering here, i.e. classes are not properly resolved only regular JTS will be kept on the class path and then the special R-tree methods required for geospark will no longer work.

**Comment by jiayuasu** [comment]
@geoHeil

**Comment by jiayuasu** [comment]
Hi @geoHeil , please add the following code (an example) in POM.xml to exclude the JTS packaged in Geotools:
```
		<dependency>
			<groupId>org. geotools </groupId>
			<artifactId> geotools </artifactId>
			<version>YOURVERSION</version>
			<exclusions>
				<exclusion>
			<groupId>com.vividsolutions</groupId>
			<artifactId>jts</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

If you are using SBT, there should be a similar way to exclude JTS package.

**Comment by geoHeil** [comment]
@jiayuasu , I saw your exclusion rule and tried to apply like:

```
libraryDependencies ++= Seq(
  "org.geotools" % "gt-main" % geotools,
  "org.geotools" % "gt-arcgrid" % geotools,
  "org.geotools" % "gt-process-raster" % geotools)
  .map(_.excludeAll(
    ExclusionRule(organization = "com.vividsolution", artifact = "jts")
  ))
```
but this does not work. To see that looks like the same formulation in maven.

**Comment by geoHeil** [comment]
Finally solved via http://stackoverflow.com/questions/43414855/sbt-transitive-dependency-resolution-conflict
